List questions_list = [
  {
    'question': 'What language do you prefer?',
    'option1': 'English',
    'option2': 'Hindi',
    'option3': 'Punjabi',
    'option4': 'Spanish',
  },
  {
    'question': 'What is the vibe?',
    'option1': 'Happy',
    'option2': 'Sad',
    'option3': 'Romantic',
    'option4': 'Party',
  },
  {
    'question': 'What brings you joy?',
    'option1': 'Bollywood movies',
    'option2': 'Dancing',
    'option3': 'Traveling',
    'option4': 'Work',
  },
  {
    'question': 'What was your favorite Bollywood era?',
    'option1': 'The 90s',
    'option2': '2000s',
    'option3': '2010s',
    'option4': 'It is at its peak right now!',
  },
  {
    'question': 'What is this playlist for?',
    'option1': 'Party',
    'option2': 'Family get-togehter',
    'option3': 'Solo chill',
    'option4': 'Traveling',
  },
  {
    'question': 'What is the party about?',
    'option1': 'House party',
    'option2': 'Kitty party',
    'option3': 'Birthday party',
    'option4': 'General party',
  },
  {
    'question': 'if you are alone what do you listen to most?',
    'option1': 'Romance',
    'option2': 'Sad',
    'option3': 'Dance',
    'option4': 'Chill',
  },
];
