// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh0jRfE0tf7pPsQc961MpM88DESKndIQ0',
    appId: '1:285117966360:web:e611401fcdb80641417b6d',
    messagingSenderId: '285117966360',
    projectId: 'new-app-69bj420',
    authDomain: 'new-app-69bj420.firebaseapp.com',
    storageBucket: 'new-app-69bj420.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ofVdYj6QDgt3zDqo3k3liZvFP0ArtL0',
    appId: '1:285117966360:android:bbcb1b06c7f1f1b5417b6d',
    messagingSenderId: '285117966360',
    projectId: 'new-app-69bj420',
    storageBucket: 'new-app-69bj420.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChPJ2aAqYxlmxU0aKjoiiQ8g4-ZZCy698',
    appId: '1:285117966360:ios:eccd2312629c5653417b6d',
    messagingSenderId: '285117966360',
    projectId: 'new-app-69bj420',
    storageBucket: 'new-app-69bj420.appspot.com',
    iosClientId: '285117966360-mocfg1dohmsohdbhvqdaf3jr5idtedsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChPJ2aAqYxlmxU0aKjoiiQ8g4-ZZCy698',
    appId: '1:285117966360:ios:eccd2312629c5653417b6d',
    messagingSenderId: '285117966360',
    projectId: 'new-app-69bj420',
    storageBucket: 'new-app-69bj420.appspot.com',
    iosClientId: '285117966360-mocfg1dohmsohdbhvqdaf3jr5idtedsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibe',
  );
}
